const modulePath=process.env.PLAYWRIGHT_MODULE_PATH || require('node:path').join(process.env.USERPROFILE,'.cache','codex-runtimes','codex-primary-runtime','dependencies','node','node_modules','playwright');
const { chromium } = require(modulePath);
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1600,height:1000},reducedMotion:'reduce'});
  const page=await context.newPage();
  const errors=[], failures=[];
  let expectedFailure='';
  page.on('pageerror',error=>errors.push(error.message));
  page.on('response',response=>{if(response.status()>=400 && response.url()!==expectedFailure)failures.push(response.url()+': '+response.status());});
  const target=process.env.OVERVIEW_URL || 'http://127.0.0.1:5001/';
  const prefix=process.env.OVERVIEW_ARTIFACT_PREFIX || 'premium-overview';
  await page.goto(target);
  await page.locator('#overviewBalanceChart').waitFor({state:'visible'});
  await page.waitForFunction(()=>window.Chart && Chart.getChart('overviewBalanceChart'));
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  const baseline=await page.locator('.ov-total').textContent();
  expectedFailure=new URL('/overview/balance?range=1w',target).href;
  await page.route('**/overview/balance?range=1w',route=>route.fulfill({status:503,body:'Unavailable'}));
  await page.locator('[data-balance-range="1w"]').click();
  await page.getByText('Balance history could not be loaded.',{exact:false}).waitFor();
  assert.equal(await page.locator('.ov-total').textContent(),baseline);
  await page.unroute('**/overview/balance?range=1w');
  await page.locator('[data-balance-state] button').click();
  await page.waitForFunction(()=>document.querySelector('[data-balance-state]').hidden);
  expectedFailure='';
  for (const range of ['1w','1m','3m','1y','all']) {
    await page.locator('[data-balance-range="'+range+'"]').click();
    await page.waitForFunction(range=>document.querySelector('[data-balance-range="'+range+'"]').getAttribute('aria-pressed')==='true' && !document.querySelector('.ov-balance-visual').hasAttribute('aria-busy'),range);
    assert.equal(await page.locator('.ov-total').textContent(),baseline);
    const reconciles=await page.evaluate(()=>{const chart=Chart.getChart('overviewBalanceChart');const data=JSON.parse(document.querySelector('#overview-data').textContent);return chart.data.datasets[0].data.at(-1).y===data.history.total;});
    assert.ok(reconciles);
  }
  await page.locator('[data-balance-privacy]').click();
  assert.ok(!(await page.locator('.ov-total').textContent()).includes('€'));
  await page.locator('[data-balance-range="1m"]').click();
  await page.waitForFunction(()=>!document.querySelector('.ov-balance-visual').hasAttribute('aria-busy'));
  assert.ok(!(await page.locator('[data-hero-change]').textContent()).includes('€'));
  await page.locator('[data-balance-privacy]').click();
  assert.equal(await page.locator('.ov-total').textContent(),baseline);
  for (const metric of ['expenses','net','income']) {
    await page.locator('[data-flow-metric="'+metric+'"]').click();
    assert.equal(await page.locator('[data-flow-metric="'+metric+'"]').getAttribute('aria-pressed'),'true');
  }
  await page.locator('[data-flow-months]').selectOption('12');
  await page.waitForFunction(()=>!document.querySelector('.ov-cashflow').hasAttribute('aria-busy'));
  assert.equal(await page.evaluate(()=>Chart.getChart('overviewFlowChart').data.labels.length),12);
  await page.locator('[data-flow-months]').selectOption('6');
  await page.waitForFunction(()=>!document.querySelector('.ov-cashflow').hasAttribute('aria-busy'));
  await page.locator('[data-balance-range="3m"]').click();
  await page.waitForFunction(()=>!document.querySelector('.ov-balance-visual').hasAttribute('aria-busy'));
  await page.locator('[data-safe-info]').click();
  assert.ok(await page.locator('[data-safe-dialog]').evaluate(e=>e.open));
  await page.locator('[data-safe-close]').click();
  await page.keyboard.press('Control+k');
  assert.ok(await page.locator('[data-command-palette]').evaluate(e=>e.open));
  await page.locator('[data-command-input]').fill('no matching merchant abc');
  assert.ok(await page.locator('[data-command-search]').isVisible());
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.querySelector('[data-command-palette]').open);
  await page.locator('.ov-add').click();
  assert.ok(await page.locator('[data-quick-add-dialog]').evaluate(e=>e.open));
  await page.locator('[data-close-quick-add]').click();
  await page.locator('.ov-account-tile').first().click();
  assert.match(page.url(),/accounts\//);
  await page.goto(target);
  await page.waitForFunction(()=>window.Chart && Chart.getChart('overviewBalanceChart'));
  await page.screenshot({path:'artifacts/'+prefix+'-desktop.png',fullPage:true});
  const desktop=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,heroHeight:document.querySelector('.ov-hero').getBoundingClientRect().height,heroWidth:document.querySelector('.ov-hero').getBoundingClientRect().width,accounts:document.querySelectorAll('.ov-account-tile').length}));
  assert.ok(desktop.scrollWidth<=desktop.width);
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.locator('.ov-navbar .navbar-avatar').isVisible());
  const strip=page.locator('[data-account-strip]');
  if(await strip.evaluate(e=>e.scrollWidth>e.clientWidth+2)){
    await page.locator('[data-accounts-scroll="1"]').click();
    await page.waitForFunction(()=>document.querySelector('[data-account-strip]').scrollLeft>0);
  }
  await page.screenshot({path:'artifacts/'+prefix+'-mobile.png',fullPage:true});
  const mobile=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,columns:getComputedStyle(document.querySelector('.ov-kpis')).gridTemplateColumns}));
  assert.ok(mobile.scrollWidth<=mobile.width,JSON.stringify(mobile));
  assert.equal(mobile.columns.split(' ').length,2);
  assert.deepEqual(errors,[]);
  assert.deepEqual(failures,[]);
  const report={desktop,mobile,consoleErrors:errors,failedResponses:failures,verified:['all five chart ranges','chart reconciliation','balance privacy after range change','cash-flow tabs and period','safe-to-spend explanation','Ctrl+K search','quick add','account navigation','account carousel','responsive overflow','network failure and retry']};
  fs.writeFileSync('artifacts/'+prefix+'-verification.json',JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
